image: node:11.6.0

cache:
  paths:
    - node_modules/
    - client/node_modules

stages:
  - build
  - test
  - staging
  - production

Build:
  stage: build
  before_script:
    - echo "Installing dependencies"
    - npm install
    - "npm --prefix client/ install"
  script:
    - echo "Building application"
    - "npm --prefix client/ run build"

Test:
  stage: test
  script:
    - echo "Testing!"

Stage:
  stage: staging
  before_script:
    - echo "Installing dependencies"
  script:
    - echo "Uploading to Staging"

Production:
  stage: production
  before_script:
    - echo "Installing dependencies"
  script:
    - echo "Uploading to Production"
  only:
    - master
