image: node:11.6.0

cache:
  paths:
    - node_modules/
    - client/node_modules

stages:
  - build
  - test
  - staging
  - production

Build:
  stage: build
  before_script:
    - echo "Build. Installing dependencies"
  script:
    - echo "Building application"

Test:
  stage: test
  script:
    - echo "Testing stage"

Stage:
  stage: staging
  before_script:
    - echo "Stage. Installing dependencies"
  script:
    - echo "Uploading to Staging"

Production:
  stage: production
  before_script:
    - echo "Production. Installing dependencies"
  script:
    - echo "Uploading to Production"
  only:
    - master
