stages:
  - build
  - test
  - staging
  - production

Test:
  stage: test
  script:
    - echo "Testing!"

Build:
  stage: build
  before_script:
    - echo "Installing dependencies"
  #  - npm install
  #  - npm --prefix client/ install

  script:
    - echo "Building application"
    # - npm --prefix client/ run build

Stage:
  stage: staging
  before_script:
    - echo "Installing dependencies"
  script:
    - echo "Uploading to Staging"

Production:
  stage: production
  before_script:
    - echo "Installing dependencies"
  script:
    - echo "Uploading to Production"
    